
development:
  adapter: postgresql
  encoding: unicode
  database: testful_restful_crud_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: testful_restful_crud_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: testful_restful_crud_production
  pool: 5
